project:
  type: website

website:
  title: "LX 394 Lab Materials"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: lab/lab01.qmd 
        text: Lab 01
      - href: lab/lab02.qmd 
        text: Lab 02
      - href: lab/lab03.qmd
        text: Lab 03
      - href: lab/lab04.qmd
        text: Lab 04
      - href: lab/lab05.qmd
        text: Lab 05
    right:
      - href: solutions/solutions.qmd
        text: Lab Solutions
format:
  html:
    theme: cosmo