---
title: "Data Types"
subtitle: "Lab 02" 
author: "Romi Hill"
jupyter: lx394_tf
date: today
format: 
  html:
      theme: cosmo
      toc: true
      toc-depth: 3
      code-overflow: wrap
number-sections: true
highlight-style: gruvbox
editor: visual
---

# Today

1.  Downloading Homework 1
2.  Folders, Files, and Folder Structure
3.  Data Types
4.  Functions

# Downloading Homework 1

Link: <https://github.com/BU-CompLing/lx394-f26-hw1>

# Folders, Files, and Folder Structure

This will be discussed in person in lab. Here are some helpful commands when we have the discussion:

+---------------+----------------------------------------+----------------------------------+
| Command       | What it does                           | Example                          |
+===============+========================================+==================================+
| `cd`          | Changes directory                      | `cd /projectnb/lx394sh/username` |
+---------------+----------------------------------------+----------------------------------+
| `ls`          | List contents of directory             | `ls`                             |
|               |                                        |                                  |
|               |                                        | `ls projectnb/lx394sh/username`  |
+---------------+----------------------------------------+----------------------------------+
| `pwd`         | Print working directory                | `pwd`                            |
+---------------+----------------------------------------+----------------------------------+
| `mkdir`       | Create a directory in current location | `mkdir my_dir_name`              |
+---------------+----------------------------------------+----------------------------------+

: Bash Commands

Use `conda install PACKAGE` in your command line to install Python packages. If you're on Mac, use the "Terminal". If you're on Windows, use the "Anaconda Prompt" (available in Anaconda Navigator"

# Exercises: Data Types

Open a `.ipynb` file to answer the following questions! I also suggest leaving comments for your code, either through a Markdown Cell, or in-line comments in Python using `#`.

## Variables and Datatypes

4.  Provide Python code that saves a variable of the following the data types. Then, print the variable. Give a different name to each variable.

- `int`
- `float`
- `str`
- `list`
- `set`
- `bool`
- `None`

For example:

```{python}
my_int = 5
print(my_int)

my_float = 0.3
print(my_float)
```

## Types

5.  Before you run the code in Python, think about what the expected output of these commands is. Once you've thought about it, run the code.

```{python}
#| eval: FALSE
type(10.5)
```

```{python}
#| eval: FALSE
type(10)
```

```{python}
#| eval: FALSE
type("7.3")
```

```{python}
#| eval: FALSE
type(8 + 38.1)
```

```{python}
#| eval: FALSE
type([10, 5])
```

```{python}
#| eval: FALSE
type("hello")
```

```{python}
#| eval: FALSE
type(print("hello"))
```

6.  What happens when you try to apply arithmetic operator to different data types? You can use your previously defined variables to answer this question!
    1.  What happens when you multiply a `list` with an `int`?
    2.  What happens when you add a `list` with an `int`?
    3.  What happens when you multiply a `str` with an `int`?
    4.  What happens when you add a `str` with an `int`?
    5.  What happens when you add a `str` with an `list`?

For example, what happens when you run the following code?

```{python}
#| eval: FALSE
my_lst * my_int
```

**The take away message here:** When you apply an operator to two different data types, the output might not be obvious! This is called implicit type casting. You can read more about this [here](https://www.geeksforgeeks.org/python/type-conversion-in-python/).

But if you cannot be bothered/not interested, you should still always check what happens when you combine two data types. Or better yet, you can **type cast** to make explicit what you're trying to do!

# Type Casting

You can also **explicitly** convert data types.

What do the following operations do?

```{python}
#| eval: FALSE
int(-7.3)
```

```{python}
#| eval: FALSE
list('hello')
```

```{python}
#| eval: FALSE
set([1, 2, 2, 4, 5])
```

```{python}
#| eval: FALSE
set(str(7.375) + str(45))
```

# Operations on Lists

We can *index* lists.

```{python}
my_lst = [17, 22, 'a', 'r', True]
```

```{python}
my_lst[2]
```

```{python}
my_lst[0]
```

```{python}
my_lst[-1]
```

We can *slice* lists.

```{python}
my_lst[:2]
```

```{python}
my_lst[1:3]
```

We can specify the *steps*

```{python}
my_lst[::2]
```

We can *reverse* lists

```{python}
my_lst[::-1]
```

We can reverse and specify the number of steps

```{python}
my_lst[::-2]
```

# Functions

Recall functions:

```{python}
def frequency(corpus, word):
    """
    Calculates the relative frequency of a word within a corpus. 

    :param corpus: An NLTK Text containing a corpus
    :param word: A word to search for in the corpus

    :return: The proportion of words in corpus that match word
    """
    return corpus.count(word) / len(corpus)
```

7.  What is a function? What are some of the components of a function?

8.  Write a function that outputs the following

```{python}
#| echo: FALSE
def print_hello(name):
    return 'Hello ' + name + '!'
```

```{python}
print_hello('Romi')
```

I'll give you the start. Hint: you need to use an operator.

```{python}
#| eval: FALSE
def print_hello(name):
    pass # replace pass with your statement
```

**Additional Exercise:**

Modify the code so that the *default* value is "Sophie". That is, your function should have the following output given these inputs. This should only take 9 characters to type!

```{python}
#| echo: FALSE
def print_hello(name = "Sophie"):
    return 'Hello ' + name + '!'
```

```{python}
print_hello()
```

```{python}
print_hello("class of LX394")
```

# Putting it together: Functions, Palindrones, and Anagrams

9.  Based on the code provided below, write a function that returns `True` when `x` and `y` are anagrams of each other, and false otherwise. Example input and expected output is provided below.

*Note:* You may have noticed `: str` and `-> bool` in this sample code. It's good style to yourself/anyone else using the code that the input parameters should be a `str`, and the output should be a `bool`. However, this is not necessary. In fact, Python will still run if the output is not a `bool`, for example.

```{python}
def is_anagram(first_word: str, second_word: str) -> bool:
    """
    Check whether two strings are palidrones of each other. 
    An anagram is formed by rearranging the letters of one word to produce another.
    """
    pass
```

```{python}
#| echo: FALSE
def is_anagram(first_word: str, second_word: str) -> bool:
    return set(first_word) == set(second_word)
```

```{python}
is_anagram('listen', 'silent')
```

```{python}
is_anagram('listen', 'listened')
```

**Challenge question:**

Modify your code so that it also ignores spaces and capitalization. For example:

```{python}
#| echo: FALSE
def is_anagram(first_word: str, second_word: str) -> bool:
    """
    Check whether two strings are palidrones of each other. 
    An anagram is formed by rearranging the letters of one word or phrase to produce another, ignoring spaces and capitalization.
    """
    first_word = first_word.lower().replace(' ', '')
    second_word = second_word.lower().replace(' ', '')

    return set(first_word) == set(second_word)
```

```{python}
is_anagram('Listen', 'siLeNt')
```

```{python}
is_anagram('Tom Marvolo Riddle', 'I am Lord Voldemort')
```

10. Based on the code provided below, write a function that returns `True` when `x` is a palindrone. Example input and expected output is provided below.

```{python}
def is_palindrone(word: str) -> bool:
    """
    Check whether a word is a palindrone
    A palindrone is a word that is spelt the same backwards and forward 
    """
    pass
```

```{python}
#| echo: FALSE
def is_palindrone(word: str) -> bool:
    return word == word[::-1]
```

```{python}
is_palindrone('racecar')
```

```{python}
is_palindrone('hello')
```